---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache.
      yum: 
        name: ['httpd','php','php-mysql'] 
        state: present
    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-5.0.2.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract WordPress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
      args:
        warn: no
    - name: Make my directory tree readable
      file:
        path: /var/www/html/
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: apache
        group: apache
    - name: Make sure Apache is started now and at boot.
      service: 
       name: httpd 
       state:  started 
       enabled: yes
